import os
"""
Django settings for poetry_site project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wtwm-oq3@-9e52&e32i@^g@&3vls^vf(+%=rz!hs!)3dg045+-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
'simpleui',
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'users',
'poetry',
]

MIDDLEWARE = [
'django.middleware.security.SecurityMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'poetry_site.urls'

TEMPLATES = [
{
'BACKEND': 'django.template.backends.django.DjangoTemplates',
'DIRS': [],
'APP_DIRS': True,
'OPTIONS': {
'context_processors': [
'django.template.context_processors.request',
'django.contrib.auth.context_processors.auth',
'django.contrib.messages.context_processors.messages',
],
},
},
]

WSGI_APPLICATION = 'poetry_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
'default': {
'ENGINE': 'django.db.backends.sqlite3',
'NAME': BASE_DIR / 'db.sqlite3',
}
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
{
'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
},
{
'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
},
{
'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
},
{
'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
},
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'





# simpleui 后台配置
SIMPLEUI_CONFIG = {
    
    "menus": [
        {
            "app": "auth",
            "name": "用户管理",
            "icon": "fas fa-users-cog",
            "models": [
                {
                    "name": "用户信息",
                    "icon": "fas fa-user",
                    "url": "/admin/auth/user/",
                }
            ]
        }
    ]
}

SIMPLEUI_HOME_PAGE = "/admin/auth/user/"
SIMPLEUI_HOME_TITLE = "后台管理"
SIMPLEUI_HOME_ICON = "fas fa-home"
SIMPLEUI_LOGO = "https://img.icons8.com/fluency/96/book.png"
SIMPLEUI_ANALYSIS = False
SIMPLEUI_DEFAULT_ICON = False


# simpleui 后台配置
SIMPLEUI_HOME_PAGE = "/admin/auth/user/"
SIMPLEUI_HOME_TITLE = "后台管理"
SIMPLEUI_HOME_ICON = "fas fa-home"
SIMPLEUI_LOGO = "https://img.icons8.com/fluency/96/book.png"
SIMPLEUI_CONFIG = {
    
    "menus": [
        {
            "name": "用户管理",
            "icon": "fas fa-users-cog",
            "models": [
                {
                    "name": "用户信息",
                    "icon": "fas fa-user",
                    "url": "/admin/auth/user/",
                }
            ]
        }
    ]
}




# simpleui 配置
SIMPLEUI_HOME_PAGE = "/admin/auth/user/"
SIMPLEUI_HOME_TITLE = "后台管理"
SIMPLEUI_LOGO = "https://img.icons8.com/fluency/96/book.png"

# Django admin 自定义
ADMIN_SITE_HEADER = "诗词鉴赏交流 - 用户管理"
ADMIN_SITE_TITLE = "后台管理"
ADMIN_INDEX_TITLE = "用户管理"
SIMPLEUI_CONFIG = {
    "system_keep": False,
    "menus": [
        {
            "name": "用户管理",
            "icon": "fas fa-users-cog",
            "models": [
                {
                    "name": "用户信息",
                    "icon": "fas fa-user",
                    "url": "/admin/auth/user/",
                }
            ]
        }
    ]
}

# ===== 生产环境部署配置 =====
import mimetypes
mimetypes.add_type("text/css", ".css", True)

# 静态文件收集目录
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MIDDLEWARE = ['whitenoise.middleware.WhiteNoiseMiddleware'] + MIDDLEWARE

# PythonAnywhere 部署
ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = []
